using BroadcastPlayout.Models;
using Microsoft.Data.Sqlite;
namespace BroadcastPlayout.Services;

public sealed record AsRunRecord(long Id,string SessionId,string ChannelId,string PlaylistItemId,string Title,string EventType,string SourcePath,string PlannedStart,string PlannedDuration,string ActualStartUtc,string ActualEndUtc,string Result,string Notes);
public sealed class AsRunLogService
{
    public static string DatabasePath=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"KashtrixPlayout","asrun.db");
    private readonly string _cs=$"Data Source={DatabasePath};Mode=ReadWriteCreate;Cache=Shared";
    private readonly Dictionary<Guid,(long Id,string Session)> _active=new();
    public AsRunLogService(){Directory.CreateDirectory(Path.GetDirectoryName(DatabasePath)!);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="""
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS asrun(id INTEGER PRIMARY KEY AUTOINCREMENT,session_id TEXT NOT NULL,channel_id TEXT NOT NULL,playlist_item_id TEXT NOT NULL,title TEXT NOT NULL,event_type TEXT NOT NULL,source_path TEXT NOT NULL,planned_start TEXT NOT NULL,planned_duration TEXT NOT NULL,actual_start_utc TEXT NOT NULL,actual_end_utc TEXT NOT NULL DEFAULT '',result TEXT NOT NULL DEFAULT 'ON AIR',notes TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS ix_asrun_channel_start ON asrun(channel_id,actual_start_utc DESC);
CREATE INDEX IF NOT EXISTS ix_asrun_item ON asrun(playlist_item_id);
""";cmd.ExecuteNonQuery();}
    private SqliteConnection Open(){var c=new SqliteConnection(_cs);c.Open();return c;}
    public void Start(string channelId,PlaylistItem item){var session=Guid.NewGuid().ToString("N");using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO asrun(session_id,channel_id,playlist_item_id,title,event_type,source_path,planned_start,planned_duration,actual_start_utc,result,notes) VALUES($s,$c,$i,$t,$e,$p,$ps,$pd,$a,'ON AIR',$n); SELECT last_insert_rowid();";cmd.Parameters.AddWithValue("$s",session);cmd.Parameters.AddWithValue("$c",channelId);cmd.Parameters.AddWithValue("$i",item.Id.ToString("D"));cmd.Parameters.AddWithValue("$t",item.Title??"");cmd.Parameters.AddWithValue("$e",item.EventType??"");cmd.Parameters.AddWithValue("$p",item.FilePath??"");cmd.Parameters.AddWithValue("$ps",item.StartTimeText??"");cmd.Parameters.AddWithValue("$pd",item.Duration.ToString("c"));cmd.Parameters.AddWithValue("$a",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$n",item.Notes??"");var id=Convert.ToInt64(cmd.ExecuteScalar());_active[item.Id]=(id,session);}
    public void Complete(PlaylistItem item,string result,string? note=null){if(!_active.TryGetValue(item.Id,out var a))return;using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE asrun SET actual_end_utc=$e,result=$r,notes=CASE WHEN $n='' THEN notes ELSE notes || ' · ' || $n END WHERE id=$id";cmd.Parameters.AddWithValue("$e",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$r",string.IsNullOrWhiteSpace(result)?"COMPLETED":result.Trim().ToUpperInvariant());cmd.Parameters.AddWithValue("$n",note??"");cmd.Parameters.AddWithValue("$id",a.Id);cmd.ExecuteNonQuery();_active.Remove(item.Id);}
    public IReadOnlyList<AsRunRecord> List(string? channelId=null,int limit=500){var list=new List<AsRunRecord>();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,session_id,channel_id,playlist_item_id,title,event_type,source_path,planned_start,planned_duration,actual_start_utc,actual_end_utc,result,notes FROM asrun "+(string.IsNullOrWhiteSpace(channelId)?"":"WHERE channel_id=$c ")+"ORDER BY id DESC LIMIT $l";if(!string.IsNullOrWhiteSpace(channelId))cmd.Parameters.AddWithValue("$c",channelId);cmd.Parameters.AddWithValue("$l",Math.Clamp(limit,1,10000));using var r=cmd.ExecuteReader();while(r.Read())list.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetString(8),r.GetString(9),r.GetString(10),r.GetString(11),r.GetString(12)));return list;}
    public string ExportCsv(string? channelId=null){var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"KashtrixPlayout","AsRun");Directory.CreateDirectory(folder);var path=Path.Combine(folder,$"asrun-{DateTime.Now:yyyyMMdd-HHmmss}.csv");static string Q(string s)=>"\""+(s??"").Replace("\"","\"\"")+"\"";using var w=new StreamWriter(path,false,new System.Text.UTF8Encoding(true));w.WriteLine("id,session,channel,item,title,eventType,source,plannedStart,plannedDuration,actualStartUtc,actualEndUtc,result,notes");foreach(var r in List(channelId,10000))w.WriteLine(string.Join(',',r.Id,Q(r.SessionId),Q(r.ChannelId),Q(r.PlaylistItemId),Q(r.Title),Q(r.EventType),Q(r.SourcePath),Q(r.PlannedStart),Q(r.PlannedDuration),Q(r.ActualStartUtc),Q(r.ActualEndUtc),Q(r.Result),Q(r.Notes)));return path;}
}
