using System.Security.Cryptography;
using System.Text;
using Microsoft.Data.Sqlite;

namespace BroadcastPlayout.Services;

public sealed record KashtrixUser(string Id,string Username,string DisplayName,string Role,bool Enabled,DateTime CreatedUtc,DateTime UpdatedUtc,DateTime? LastLoginUtc);
public sealed record KashtrixApiCredential(string Id,string Name,string Username,string Scopes,bool Enabled,DateTime CreatedUtc,DateTime? LastUsedUtc);
public sealed record SecurityPrincipal(string Username,string Role,string Scopes,bool IsApiUser);

public sealed class SecurityStore
{
    private const int Pbkdf2Iterations=210000;
    public static string DatabasePath=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"KashtrixPlayout","security.db");
    private string Cs=>$"Data Source={DatabasePath};Mode=ReadWriteCreate;Cache=Shared";
    public SecurityStore(){Directory.CreateDirectory(Path.GetDirectoryName(DatabasePath)!);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="""
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE COLLATE NOCASE,display_name TEXT NOT NULL,role TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,password_salt TEXT NOT NULL,password_hash TEXT NOT NULL,password_iterations INTEGER NOT NULL,created_utc TEXT NOT NULL,updated_utc TEXT NOT NULL,last_login_utc TEXT NULL);
CREATE TABLE IF NOT EXISTS api_credentials(id TEXT PRIMARY KEY,name TEXT NOT NULL,username TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,scopes TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,created_utc TEXT NOT NULL,last_used_utc TEXT NULL);
CREATE TABLE IF NOT EXISTS remembered_sessions(id TEXT PRIMARY KEY,username TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,created_utc TEXT NOT NULL,expires_utc TEXT NOT NULL,last_used_utc TEXT NULL);
CREATE INDEX IF NOT EXISTS ix_api_credentials_user ON api_credentials(username);
CREATE TABLE IF NOT EXISTS security_audit(id INTEGER PRIMARY KEY AUTOINCREMENT,utc TEXT NOT NULL,actor TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL,detail TEXT NOT NULL);
""";cmd.ExecuteNonQuery();EnsureBootstrapAdmin(c);}
    private SqliteConnection Open(){var c=new SqliteConnection(Cs);c.Open();return c;}
    private static void EnsureBootstrapAdmin(SqliteConnection c){using var count=c.CreateCommand();count.CommandText="SELECT COUNT(*) FROM users";if(Convert.ToInt32(count.ExecuteScalar())>0)return;var password="Kashtrix-"+Convert.ToHexString(RandomNumberGenerator.GetBytes(6));CreateUserCore(c,"admin","Kashtrix Administrator","ADMIN",password);var path=Path.Combine(Path.GetDirectoryName(DatabasePath)!,"FIRST-RUN-ADMIN.txt");File.WriteAllText(path,$"Kashtrix first-run administrator\r\nUsername: admin\r\nPassword: {password}\r\nChange this password immediately, then delete this file.\r\n");}
    public IReadOnlyList<KashtrixUser> ListUsers(){var list=new List<KashtrixUser>();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,username,display_name,role,enabled,created_utc,updated_utc,last_login_utc FROM users ORDER BY username";using var r=cmd.ExecuteReader();while(r.Read())list.Add(new(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetInt32(4)!=0,DateTime.Parse(r.GetString(5)).ToUniversalTime(),DateTime.Parse(r.GetString(6)).ToUniversalTime(),r.IsDBNull(7)?null:DateTime.Parse(r.GetString(7)).ToUniversalTime()));return list;}
    public KashtrixUser CreateUser(string username,string displayName,string role,string password){ValidateUsername(username);if(string.IsNullOrWhiteSpace(password)||password.Length<10)throw new InvalidOperationException("Password must be at least 10 characters.");using var c=Open();var row=CreateUserCore(c,username.Trim(),string.IsNullOrWhiteSpace(displayName)?username.Trim():displayName.Trim(),NormalizeRole(role),password);Audit(c,"SYSTEM","USER_CREATE",row.Username,row.Role);return row;}
    private static KashtrixUser CreateUserCore(SqliteConnection c,string username,string displayName,string role,string password){var salt=RandomNumberGenerator.GetBytes(32);var hash=Rfc2898DeriveBytes.Pbkdf2(password,salt,Pbkdf2Iterations,HashAlgorithmName.SHA256,32);var now=DateTime.UtcNow;var row=new KashtrixUser(Guid.NewGuid().ToString("N"),username,displayName,NormalizeRole(role),true,now,now,null);using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO users(id,username,display_name,role,enabled,password_salt,password_hash,password_iterations,created_utc,updated_utc) VALUES($id,$u,$d,$r,1,$s,$h,$i,$c,$up)";cmd.Parameters.AddWithValue("$id",row.Id);cmd.Parameters.AddWithValue("$u",row.Username);cmd.Parameters.AddWithValue("$d",row.DisplayName);cmd.Parameters.AddWithValue("$r",row.Role);cmd.Parameters.AddWithValue("$s",Convert.ToBase64String(salt));cmd.Parameters.AddWithValue("$h",Convert.ToBase64String(hash));cmd.Parameters.AddWithValue("$i",Pbkdf2Iterations);cmd.Parameters.AddWithValue("$c",now.ToString("O"));cmd.Parameters.AddWithValue("$up",now.ToString("O"));cmd.ExecuteNonQuery();CryptographicOperations.ZeroMemory(hash);return row;}
    public bool VerifyPassword(string username,string password,out SecurityPrincipal? principal){principal=null;using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT role,enabled,password_salt,password_hash,password_iterations FROM users WHERE username=$u";cmd.Parameters.AddWithValue("$u",username.Trim());using var r=cmd.ExecuteReader();if(!r.Read()||r.GetInt32(1)==0)return false;var salt=Convert.FromBase64String(r.GetString(2));var expected=Convert.FromBase64String(r.GetString(3));var actual=Rfc2898DeriveBytes.Pbkdf2(password,salt,r.GetInt32(4),HashAlgorithmName.SHA256,expected.Length);var ok=CryptographicOperations.FixedTimeEquals(actual,expected);CryptographicOperations.ZeroMemory(actual);if(!ok)return false;var role=r.GetString(0);principal=new(username,role,ScopesForRole(role),false);r.Close();using var up=c.CreateCommand();up.CommandText="UPDATE users SET last_login_utc=$u WHERE username=$n";up.Parameters.AddWithValue("$u",DateTime.UtcNow.ToString("O"));up.Parameters.AddWithValue("$n",username);up.ExecuteNonQuery();return true;}

    public static string RememberedSessionPath => Path.Combine(Path.GetDirectoryName(DatabasePath)!, "remembered-login.txt");
    public void RememberSession(SecurityPrincipal principal)
    {
        if (principal.IsApiUser || string.IsNullOrWhiteSpace(principal.Username)) return;
        var token = Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();
        var hash = TokenHash(token); var now = DateTime.UtcNow; var expires = now.AddDays(90);
        using var c = Open(); using var tx = c.BeginTransaction();
        using (var clear = c.CreateCommand()) { clear.Transaction=tx; clear.CommandText="DELETE FROM remembered_sessions WHERE username=$u OR expires_utc<$now"; clear.Parameters.AddWithValue("$u",principal.Username); clear.Parameters.AddWithValue("$now",now.ToString("O")); clear.ExecuteNonQuery(); }
        using (var cmd = c.CreateCommand()) { cmd.Transaction=tx; cmd.CommandText="INSERT INTO remembered_sessions(id,username,token_hash,created_utc,expires_utc) VALUES($id,$u,$h,$c,$e)"; cmd.Parameters.AddWithValue("$id",Guid.NewGuid().ToString("N")); cmd.Parameters.AddWithValue("$u",principal.Username); cmd.Parameters.AddWithValue("$h",hash); cmd.Parameters.AddWithValue("$c",now.ToString("O")); cmd.Parameters.AddWithValue("$e",expires.ToString("O")); cmd.ExecuteNonQuery(); }
        tx.Commit();
        Directory.CreateDirectory(Path.GetDirectoryName(RememberedSessionPath)!);
        File.WriteAllText(RememberedSessionPath, principal.Username + "\n" + token, new UTF8Encoding(false));
    }
    public bool TryRestoreRememberedSession(out SecurityPrincipal? principal)
    {
        principal=null;
        try
        {
            if(!File.Exists(RememberedSessionPath))return false;
            var lines=File.ReadAllLines(RememberedSessionPath,Encoding.UTF8);if(lines.Length<2)return false;
            var username=lines[0].Trim();var token=lines[1].Trim();if(string.IsNullOrWhiteSpace(username)||string.IsNullOrWhiteSpace(token))return false;
            using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT u.role,u.enabled,s.id,s.expires_utc FROM remembered_sessions s JOIN users u ON u.username=s.username WHERE s.username=$u AND s.token_hash=$h";cmd.Parameters.AddWithValue("$u",username);cmd.Parameters.AddWithValue("$h",TokenHash(token));using var r=cmd.ExecuteReader();if(!r.Read()||r.GetInt32(1)==0){ClearRememberedSessionFile();return false;}var expires=DateTime.Parse(r.GetString(3)).ToUniversalTime();if(expires<=DateTime.UtcNow){r.Close();ClearRememberedSessionFile();return false;}var role=r.GetString(0);var id=r.GetString(2);principal=new(username,role,ScopesForRole(role),false);r.Close();using var up=c.CreateCommand();up.CommandText="UPDATE remembered_sessions SET last_used_utc=$now WHERE id=$id";up.Parameters.AddWithValue("$now",DateTime.UtcNow.ToString("O"));up.Parameters.AddWithValue("$id",id);up.ExecuteNonQuery();return true;
        }
        catch { ClearRememberedSessionFile(); return false; }
    }
    public void ForgetRememberedSession(string? username=null)
    {
        try{using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText=string.IsNullOrWhiteSpace(username)?"DELETE FROM remembered_sessions":"DELETE FROM remembered_sessions WHERE username=$u";if(!string.IsNullOrWhiteSpace(username))cmd.Parameters.AddWithValue("$u",username);cmd.ExecuteNonQuery();}catch{}
        ClearRememberedSessionFile();
    }
    private static void ClearRememberedSessionFile(){try{if(File.Exists(RememberedSessionPath))File.Delete(RememberedSessionPath);}catch{}}

    public void ResetPassword(string username,string password,string actor="SYSTEM"){if(password.Length<10)throw new InvalidOperationException("Password must be at least 10 characters.");var salt=RandomNumberGenerator.GetBytes(32);var hash=Rfc2898DeriveBytes.Pbkdf2(password,salt,Pbkdf2Iterations,HashAlgorithmName.SHA256,32);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE users SET password_salt=$s,password_hash=$h,password_iterations=$i,updated_utc=$u WHERE username=$n";cmd.Parameters.AddWithValue("$s",Convert.ToBase64String(salt));cmd.Parameters.AddWithValue("$h",Convert.ToBase64String(hash));cmd.Parameters.AddWithValue("$i",Pbkdf2Iterations);cmd.Parameters.AddWithValue("$u",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$n",username);if(cmd.ExecuteNonQuery()==0)throw new InvalidOperationException("User not found.");using(var rs=c.CreateCommand()){rs.CommandText="DELETE FROM remembered_sessions WHERE username=$u";rs.Parameters.AddWithValue("$u",username);rs.ExecuteNonQuery();}CryptographicOperations.ZeroMemory(hash);Audit(c,actor,"PASSWORD_RESET",username,"");if(username.Equals("admin",StringComparison.OrdinalIgnoreCase)){try{var first=Path.Combine(Path.GetDirectoryName(DatabasePath)!,"FIRST-RUN-ADMIN.txt");if(File.Exists(first))File.Delete(first);}catch{}}}
    public void SetUserState(string username,string role,bool enabled,string actor="SYSTEM"){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE users SET role=$r,enabled=$e,updated_utc=$u WHERE username=$n";cmd.Parameters.AddWithValue("$r",NormalizeRole(role));cmd.Parameters.AddWithValue("$e",enabled?1:0);cmd.Parameters.AddWithValue("$u",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$n",username);cmd.ExecuteNonQuery();if(!enabled){using var rs=c.CreateCommand();rs.CommandText="DELETE FROM remembered_sessions WHERE username=$u";rs.Parameters.AddWithValue("$u",username);rs.ExecuteNonQuery();}Audit(c,actor,"USER_UPDATE",username,$"role={NormalizeRole(role)} enabled={enabled}");}
    public (KashtrixApiCredential Credential,string Token) CreateApiCredential(string name,string username,string scopes){var token="ktx_"+Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();var hash=TokenHash(token);var now=DateTime.UtcNow;var row=new KashtrixApiCredential(Guid.NewGuid().ToString("N"),string.IsNullOrWhiteSpace(name)?"API Client":name.Trim(),string.IsNullOrWhiteSpace(username)?"api":username.Trim(),NormalizeScopes(scopes),true,now,null);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO api_credentials(id,name,username,token_hash,scopes,enabled,created_utc) VALUES($id,$n,$u,$h,$s,1,$c)";cmd.Parameters.AddWithValue("$id",row.Id);cmd.Parameters.AddWithValue("$n",row.Name);cmd.Parameters.AddWithValue("$u",row.Username);cmd.Parameters.AddWithValue("$h",hash);cmd.Parameters.AddWithValue("$s",row.Scopes);cmd.Parameters.AddWithValue("$c",now.ToString("O"));cmd.ExecuteNonQuery();Audit(c,"SYSTEM","API_CREATE",row.Name,row.Scopes);return(row,token);}
    public IReadOnlyList<KashtrixApiCredential> ListApiCredentials(){var list=new List<KashtrixApiCredential>();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,name,username,scopes,enabled,created_utc,last_used_utc FROM api_credentials ORDER BY name";using var r=cmd.ExecuteReader();while(r.Read())list.Add(new(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetInt32(4)!=0,DateTime.Parse(r.GetString(5)).ToUniversalTime(),r.IsDBNull(6)?null:DateTime.Parse(r.GetString(6)).ToUniversalTime()));return list;}
    public void RevokeApiCredential(string id){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE api_credentials SET enabled=0 WHERE id=$id";cmd.Parameters.AddWithValue("$id",id);cmd.ExecuteNonQuery();Audit(c,"SYSTEM","API_REVOKE",id,"");}
    public bool VerifyApiToken(string token,out SecurityPrincipal? principal){principal=null;if(string.IsNullOrWhiteSpace(token))return false;var hash=TokenHash(token.Trim());using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,username,scopes,enabled FROM api_credentials WHERE token_hash=$h";cmd.Parameters.AddWithValue("$h",hash);using var r=cmd.ExecuteReader();if(!r.Read()||r.GetInt32(3)==0)return false;var id=r.GetString(0);principal=new(r.GetString(1),"API",r.GetString(2),true);r.Close();using var up=c.CreateCommand();up.CommandText="UPDATE api_credentials SET last_used_utc=$u WHERE id=$id";up.Parameters.AddWithValue("$u",DateTime.UtcNow.ToString("O"));up.Parameters.AddWithValue("$id",id);up.ExecuteNonQuery();return true;}
    public static bool HasScope(SecurityPrincipal principal,string required){if(principal.Role.Equals("ADMIN",StringComparison.OrdinalIgnoreCase))return true;var scopes=principal.Scopes.Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);return scopes.Contains("*",StringComparer.OrdinalIgnoreCase)||scopes.Contains(required,StringComparer.OrdinalIgnoreCase)||(required.EndsWith(":read",StringComparison.OrdinalIgnoreCase)&&scopes.Contains(required[..^5]+":write",StringComparer.OrdinalIgnoreCase));}
    private static string ScopesForRole(string role)=>NormalizeRole(role) switch{"ADMIN"=>"*","OPERATOR"=>"playout:read,playout:write,cg:read,cg:write,mam:read,nrcs:read,nrcs:write,prompter:read,ha:read","JOURNALIST"=>"nrcs:read,nrcs:write,cg:read,mam:read,prompter:read","VIEWER"=>"playout:read,cg:read,mam:read,nrcs:read,prompter:read,ha:read",_=>"playout:read"};
    private static string NormalizeRole(string? role){var r=(role??"VIEWER").Trim().ToUpperInvariant();return r is "ADMIN" or "OPERATOR" or "JOURNALIST" or "VIEWER"?r:"VIEWER";}
    private static string NormalizeScopes(string? scopes)=>string.Join(',',(scopes??"playout:read").Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Select(x=>x.ToLowerInvariant()).Distinct());
    private static void ValidateUsername(string username){if(string.IsNullOrWhiteSpace(username)||username.Trim().Length<3||username.Any(ch=>!(char.IsLetterOrDigit(ch)||ch is '.' or '_' or '-')))throw new InvalidOperationException("Username must be at least 3 characters and use letters, numbers, dot, dash or underscore.");}
    private static string TokenHash(string token)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token))).ToLowerInvariant();
    private static void Audit(SqliteConnection c,string actor,string action,string target,string detail){using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO security_audit(utc,actor,action,target,detail) VALUES($u,$a,$ac,$t,$d)";cmd.Parameters.AddWithValue("$u",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$a",actor);cmd.Parameters.AddWithValue("$ac",action);cmd.Parameters.AddWithValue("$t",target);cmd.Parameters.AddWithValue("$d",detail);cmd.ExecuteNonQuery();}
}
